# Generated by Django 3.1.7 on 2024-02-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalexperience',
            name='job',
        ),
        migrations.RemoveField(
            model_name='project',
            name='job',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='role',
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Intern', max_length=100),
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='ProfessionalExperience',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
